from django.urls import path
from .views import (
    DashboardView, FullQuoteCalculatorView, SimpleCostingCalculatorView, CalculateQuoteView, LogSaleView,
MaterialListView, MaterialCreateView, MaterialUpdateView, MaterialDeleteView, BulkMaterialDeleteView,
MaterialExportExcelView, MaterialImportExcelView,
    StickerSizeListView, StickerSizeCreateView, StickerSizeUpdateView, StickerSizeDeleteView, BulkStickerSizeDeleteView,
PaperSizeListView, PaperSizeCreateView, PaperSizeUpdateView, PaperSizeDeleteView,
PaperSizeExportExcelView, PaperSizeImportExcelView,
    PriceSettingsView, SalesLogView, SalesLogExportExcelView, SalesLogImportExcelView, SaleLogDeleteView, SaleLogUpdateView, SaleLogDetailView,
    SaleReceiptView, ProductCatalogView, ProductPresetCreateView, ProductPresetUpdateView, ProductPriceTierCreateView, ProductQuoteView, ProductCategoryCreateView, OrderQueueView, UpdateJobStatusView, CustomerHistoryView, ReorderSaleView, ExpenseListView, StockPurchaseListView, ShopTaskListView, JobTicketView, CashflowView, AnalyticsDashboardView, SmartBusinessView, CustomerOrderPageView, CustomerOrderCreateView, CustomerQueueDataView, CustomerOrderQueueView, StaffQueueDataView, CustomerOrderActionView, CustomerOrderNotesView, CustomerOrderReceiptRedirectView, FastPOSView, POSCreateOrderView, POSQueueDataView, POSQueueStatusView, POSReceiptView, POSSalesDashboardView, QuickPOSProductListView, QuickPOSProductCreateView, QuickPOSProductUpdateView, POSProductInlineCreateView, POSProductInlineUpdateView, POSProductToggleView, POSProductDeleteView, POSCategoryCreateView, CreatePOSPriceSnapshotView, SmartPasteView, SmartPasteInquiryUpdateView, SmartPasteInquiryDeleteView
)

urlpatterns = [
    path('', DashboardView.as_view(), name='dashboard'),
    path('quote-calculator/', FullQuoteCalculatorView.as_view(), name='quote_calculator'),
    path('simple-costing/', SimpleCostingCalculatorView.as_view(), name='simple_costing_calculator'),
    path('calculate-quote/', CalculateQuoteView.as_view(), name='calculate_quote'),
    path('log-sale/', LogSaleView.as_view(), name='log_sale'),
    path('sales/', SalesLogView.as_view(), name='sales_log'),
    path('sales/export-excel/', SalesLogExportExcelView.as_view(), name='sales_export_excel'),
    path('sales/import-excel/', SalesLogImportExcelView.as_view(), name='sales_import_excel'),
    path('queue/', OrderQueueView.as_view(), name='order_queue'),
    path('queue/<int:pk>/status/', UpdateJobStatusView.as_view(), name='update_job_status'),
    path('customers/<str:customer_name>/', CustomerHistoryView.as_view(), name='customer_history'),
    path('sales/<int:pk>/reorder/', ReorderSaleView.as_view(), name='sale_reorder'),
    path('sales/<int:pk>/job-ticket/', JobTicketView.as_view(), name='job_ticket'),
    path('expenses/', ExpenseListView.as_view(), name='expenses'),
    path('stock-purchases/', StockPurchaseListView.as_view(), name='stock_purchases'),
    path('tasks/', ShopTaskListView.as_view(), name='tasks'),
    path('cashflow/', CashflowView.as_view(), name='cashflow'),
    path('analytics/', AnalyticsDashboardView.as_view(), name='analytics_dashboard'),
    path('smart-business/', SmartBusinessView.as_view(), name='smart_business'),
    path('smart-paste/', SmartPasteView.as_view(), name='smart_paste'),
    path('smart-paste/<int:pk>/edit/', SmartPasteInquiryUpdateView.as_view(), name='smart_paste_edit'),
    path('smart-paste/<int:pk>/delete/', SmartPasteInquiryDeleteView.as_view(), name='smart_paste_delete'),
    path('customer-order/', CustomerOrderPageView.as_view(), name='customer_order'),
    path('customer-order/create/', CustomerOrderCreateView.as_view(), name='customer_order_create'),
    path('customer-order/queue-data/', CustomerQueueDataView.as_view(), name='customer_queue_data'),
    path('pos/order-queue/', CustomerOrderQueueView.as_view(), name='customer_order_queue'),
    path('pos/order-queue/data/', StaffQueueDataView.as_view(), name='staff_queue_data'),
    path('pos/order-queue/<int:pk>/action/', CustomerOrderActionView.as_view(), name='customer_order_action'),
    path('pos/order-queue/<int:pk>/notes/', CustomerOrderNotesView.as_view(), name='customer_order_notes'),
    path('pos/order-queue/<int:pk>/receipt/', CustomerOrderReceiptRedirectView.as_view(), name='customer_order_receipt'),
    path('pos/', FastPOSView.as_view(), name='fast_pos'),
    path('pos/orders/create/', POSCreateOrderView.as_view(), name='pos_order_create'),
    path('pos/queue/data/', POSQueueDataView.as_view(), name='pos_queue_data'),
    path('pos/queue/<int:pk>/status/', POSQueueStatusView.as_view(), name='pos_queue_status'),
    path('pos/orders/<int:pk>/receipt/', POSReceiptView.as_view(), name='pos_receipt'),
    path('pos/dashboard/', POSSalesDashboardView.as_view(), name='pos_sales_dashboard'),
    path('pos/products/', QuickPOSProductListView.as_view(), name='pos_products'),
    path('pos/products/add/', QuickPOSProductCreateView.as_view(), name='pos_product_add'),
    path('pos/products/quick-add/', POSProductInlineCreateView.as_view(), name='pos_product_quick_add'),
    path('pos/products/<int:pk>/edit/', QuickPOSProductUpdateView.as_view(), name='pos_product_edit'),
    path('pos/products/<int:pk>/quick-edit/', POSProductInlineUpdateView.as_view(), name='pos_product_quick_edit'),
    path('pos/products/<int:pk>/toggle/', POSProductToggleView.as_view(), name='pos_product_toggle'),
    path('pos/products/<int:pk>/delete/', POSProductDeleteView.as_view(), name='pos_product_delete'),
    path('pos/categories/add/', POSCategoryCreateView.as_view(), name='pos_category_add'),
    path('pos/products/<int:pk>/snapshot/', CreatePOSPriceSnapshotView.as_view(), name='pos_product_snapshot'),


    path('materials/', MaterialListView.as_view(), name='materials'),
    path('materials/add/', MaterialCreateView.as_view(), name='material_add'),
    path('materials/<int:pk>/edit/', MaterialUpdateView.as_view(), name='material_edit'),
    path('materials/<int:pk>/delete/', MaterialDeleteView.as_view(), name='material_delete'),
    path('materials/bulk-delete/', BulkMaterialDeleteView.as_view(), name='material_bulk_delete'),
    path('materials/export-excel/', MaterialExportExcelView.as_view(), name='material_export_excel'),
    path('materials/import-excel/', MaterialImportExcelView.as_view(), name='material_import_excel'),

    path('sticker-sizes/', StickerSizeListView.as_view(), name='sticker_sizes'),
    path('sticker-sizes/add/', StickerSizeCreateView.as_view(), name='sticker_size_add'),
    path('sticker-sizes/<int:pk>/edit/', StickerSizeUpdateView.as_view(), name='sticker_size_edit'),
    path('sticker-sizes/<int:pk>/delete/', StickerSizeDeleteView.as_view(), name='sticker_size_delete'),
    path('sticker-sizes/bulk-delete/', BulkStickerSizeDeleteView.as_view(), name='sticker_size_bulk_delete'),

    path('paper-sizes/', PaperSizeListView.as_view(), name='paper_sizes'),
    path('paper-sizes/add/', PaperSizeCreateView.as_view(), name='paper_size_add'),
    path('paper-sizes/<int:pk>/edit/', PaperSizeUpdateView.as_view(), name='paper_size_edit'),
    path('paper-sizes/<int:pk>/delete/', PaperSizeDeleteView.as_view(), name='paper_size_delete'),
    path('paper-sizes/export-excel/', PaperSizeExportExcelView.as_view(), name='paper_size_export_excel'),
    path('paper-sizes/import-excel/', PaperSizeImportExcelView.as_view(), name='paper_size_import_excel'),

    path('settings/', PriceSettingsView.as_view(), name='price_settings'),
    path('products/', ProductCatalogView.as_view(), name='product_catalog'),
    path('products/quote/', ProductQuoteView.as_view(), name='product_quote'),
    path('products/add/', ProductPresetCreateView.as_view(), name='product_add'),
    path('products/category/add/', ProductCategoryCreateView.as_view(), name='product_category_add'),
    path('products/tier/add/', ProductPriceTierCreateView.as_view(), name='product_tier_add'),
    path('products/<int:pk>/edit/', ProductPresetUpdateView.as_view(), name='product_edit'),
    path("sales/<int:pk>/delete/", SaleLogDeleteView.as_view(), name="sale_delete"),
    path("sales/<int:pk>/edit/", SaleLogUpdateView.as_view(), name="sale_edit"),
    path("sales/<int:pk>/", SaleLogDetailView.as_view(), name="sale_detail"),
    path("sales/<int:pk>/receipt/", SaleReceiptView.as_view(), name="sale_receipt"),
]
