# Generated for local costing calculator
from django.db import migrations, models
import django.db.models.deletion
import decimal

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='EquipmentOverhead', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=100)),('monthly_cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),('notes', models.TextField(blank=True))]),
        migrations.CreateModel(name='Material', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('category', models.CharField(choices=[('Sticker Paper', 'Sticker Paper / Main Material'), ('Lamination', 'Lamination / Photo Top'), ('Packaging', 'Packaging'), ('Ink', 'Ink'), ('Other', 'Other')], max_length=40)),('item_name', models.CharField(max_length=180, unique=True)),('pack_price', models.DecimalField(decimal_places=2, max_digits=12)),('pack_qty', models.DecimalField(decimal_places=2, max_digits=12)),('unit', models.CharField(max_length=40)),('use_type', models.CharField(choices=[('Direct Material', 'Direct Material'), ('Equipment', 'Equipment'), ('Tool', 'Tool')], default='Direct Material', max_length=40)),('is_active', models.BooleanField(default=True)),('notes', models.TextField(blank=True))], options={'ordering': ['category', 'item_name']}),
        migrations.CreateModel(name='PaperSize', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=80, unique=True)),('width_in', models.DecimalField(decimal_places=2, max_digits=7)),('height_in', models.DecimalField(decimal_places=2, max_digits=7)),('cricut_safe_width_in', models.DecimalField(decimal_places=2, max_digits=7)),('cricut_safe_height_in', models.DecimalField(decimal_places=2, max_digits=7)),('is_active', models.BooleanField(default=True))], options={'ordering': ['name']}),
        migrations.CreateModel(name='PriceSetting', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('orders_per_month', models.DecimalField(decimal_places=2, default=decimal.Decimal('30.00'), max_digits=10)),('labor_rate_per_hour', models.DecimalField(decimal_places=2, default=decimal.Decimal('80.00'), max_digits=10)),('default_ink_cost_per_sheet', models.DecimalField(decimal_places=2, default=decimal.Decimal('3.00'), max_digits=10)),('default_markup_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('20.00'), max_digits=7)),('default_margin_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('15.00'), max_digits=7)),('default_discount_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=7)),('default_sales_tax_percent', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=7)),('safety_buffer_per_order', models.DecimalField(decimal_places=2, default=decimal.Decimal('5.00'), max_digits=10)),('additional_direct_cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.08'), max_digits=10))]),
        migrations.CreateModel(name='SaleLog', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('created_at', models.DateTimeField(auto_now_add=True)),('customer_name', models.CharField(blank=True, max_length=120)),('order_name', models.CharField(blank=True, max_length=120)),('sticker_size', models.CharField(blank=True, max_length=120)),('quantity', models.PositiveIntegerField(default=0)),('selling_price', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),('sales_tax', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),('cost', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),('profit', models.DecimalField(decimal_places=2, default=decimal.Decimal('0.00'), max_digits=12)),('payment_method', models.CharField(default='Cash', max_length=80)),('status', models.CharField(default='Logged', max_length=80)),('notes', models.TextField(blank=True))], options={'ordering': ['-created_at']}),
        migrations.CreateModel(name='StickerSize', fields=[('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),('name', models.CharField(max_length=100)),('width_in', models.DecimalField(decimal_places=2, max_digits=7)),('height_in', models.DecimalField(decimal_places=2, max_digits=7)),('use_cricut_safe_area', models.BooleanField(default=True)),('is_active', models.BooleanField(default=True)),('notes', models.TextField(blank=True)),('paper_size', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sticker_sizes', to='costing.papersize'))], options={'ordering': ['width_in', 'height_in']}),
    ]
