# Generated by Django 5.2.13 on 2026-04-25 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papersize',
            name='cricut_safe_height_in',
        ),
        migrations.RemoveField(
            model_name='papersize',
            name='cricut_safe_width_in',
        ),
        migrations.AddField(
            model_name='papersize',
            name='use_cricut_safe_area',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='papersize',
            name='height_in',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='papersize',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='papersize',
            name='width_in',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stickersize',
            name='height_in',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='stickersize',
            name='paper_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='costing.papersize'),
        ),
        migrations.AlterField(
            model_name='stickersize',
            name='width_in',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
