# Generated by Django 5.2.13 on 2026-04-25 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0002_remove_papersize_cricut_safe_height_in_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='packaging_capacity',
            field=models.PositiveIntegerField(default=1, help_text='For packaging only. Example: if 1 OPP bag fits 2 stickers, enter 2.'),
        ),
    ]
