# Generated by Django 5.2.13 on 2026-04-25 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0003_material_packaging_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='packaging_capacity',
            field=models.PositiveIntegerField(default=1, help_text='For packaging only. Example: 1 OPP bag can hold 2 stickers, enter 2.'),
        ),
    ]
