# Generated by Django 5.2.13 on 2026-04-25 20:25

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0004_alter_material_packaging_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='buyer_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='salelog',
            name='buyer_username',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salelog',
            name='courier',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='salelog',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salelog',
            name='platform',
            field=models.CharField(choices=[('Walk-in', 'Walk-in'), ('Shopee', 'Shopee'), ('Lazada', 'Lazada'), ('TikTok Shop', 'TikTok Shop'), ('Facebook', 'Facebook'), ('Instagram', 'Instagram'), ('Other', 'Other')], default='Walk-in', max_length=50),
        ),
        migrations.AddField(
            model_name='salelog',
            name='platform_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salelog',
            name='platform_order_id',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salelog',
            name='receipt_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='shipping_address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='shipping_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salelog',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='salelog',
            name='weight_grams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='salelog',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('GCash', 'GCash'), ('Bank Transfer', 'Bank Transfer'), ('COD', 'COD'), ('Platform Payment', 'Platform Payment'), ('Other', 'Other')], default='Cash', max_length=80),
        ),
        migrations.AlterField(
            model_name='salelog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Packing', 'Packing'), ('Shipped', 'Shipped'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Refunded', 'Refunded')], default='Pending', max_length=80),
        ),
    ]
