# Generated by Django 5.2.13 on 2026-04-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0005_salelog_buyer_phone_salelog_buyer_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='packaging_capacity',
            field=models.PositiveIntegerField(blank=True, default=1, help_text='For packaging only. Example: 1 OPP bag can hold 2 stickers, enter 2.', null=True),
        ),
    ]
