# Generated by Django 5.2.13 on 2026-04-25 23:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0006_alter_material_packaging_capacity'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleLogItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.PositiveIntegerField(default=1)),
                ('line_id', models.CharField(blank=True, max_length=80, unique=True)),
                ('sku', models.CharField(blank=True, max_length=80)),
                ('product_name', models.CharField(blank=True, max_length=120)),
                ('sticker_size', models.CharField(blank=True, max_length=120)),
                ('material_name', models.CharField(blank=True, max_length=180)),
                ('lamination_name', models.CharField(blank=True, max_length=180)),
                ('packaging_name', models.CharField(blank=True, max_length=180)),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sheets_needed', models.PositiveIntegerField(default=0)),
                ('packaging_capacity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.salelog')),
            ],
            options={
                'ordering': ['line_number'],
            },
        ),
    ]
