# Generated by Django 5.2.13 on 2026-04-26 01:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0007_salelogitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='stock_qty',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock on hand. Example: sheets, pcs, bags.', max_digits=12),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='lamination',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_lamination_items', to='costing.material'),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='lamination_qty_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_material_items', to='costing.material'),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='material_qty_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='packaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_packaging_items', to='costing.material'),
        ),
        migrations.AddField(
            model_name='salelogitem',
            name='packaging_qty_used',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
