# Generated by Django 5.2.13 on 2026-05-01 02:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0014_v5_smart_paste'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricesetting',
            name='default_margin_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('35.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='default_markup_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('45.00'), max_digits=7),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='minimum_order_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('149.00'), help_text='Lowest allowed product selling price before shipping/tax.', max_digits=10),
        ),
        migrations.AlterField(
            model_name='pricesetting',
            name='safety_buffer_per_order',
            field=models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=10),
        ),
    ]
