# Generated by Django 5.2.13 on 2026-05-02 07:41

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0015_alter_pricesetting_default_margin_percent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='reorder_level',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Optional low stock warning level.', max_digits=12, null=True),
        ),
    ]
