# Generated by Django 5.2.13 on 2026-05-18 20:32

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


def seed_pos_catalog(apps, schema_editor):
    POSCategory = apps.get_model('costing', 'POSCategory')
    POSProduct = apps.get_model('costing', 'POSProduct')

    categories = {
        "Drinks": ("DRINK", "Matcha and tea drinks prepared by the barista."),
        "Stickers": ("STICKER", "Sticker sheets and individual sticker products."),
        "Cookies": ("COOKIE", "Cookie flavors for counter sales."),
        "Add-ons": ("ADDON", "Drink add-ons and modifiers."),
    }
    category_objects = {}
    for name, (category_type, description) in categories.items():
        category, _ = POSCategory.objects.update_or_create(
            name=name,
            defaults={"category_type": category_type, "description": description, "is_active": True},
        )
        category_objects[name] = category

    products = [
        ("Drinks", "Matcha Latte", "60.00", True, 0, "0.00"),
        ("Drinks", "Strawberry Matcha", "70.00", True, 0, "0.00"),
        ("Drinks", "Hojicha", "100.00", True, 0, "0.00"),
        ("Drinks", "Premium Matcha Bliss", "200.00", True, 0, "0.00"),
        ("Stickers", "Waterproof Sticker Sheets", "60.00", False, 0, "0.00"),
        ("Stickers", "Holographic Rainbow Stickers", "30.00", False, 5, "125.00"),
        ("Cookies", "Chocolate Chip Cookie", "45.00", False, 0, "0.00"),
        ("Cookies", "Matcha Cookie", "45.00", False, 0, "0.00"),
        ("Cookies", "Red Velvet Cookie", "45.00", False, 0, "0.00"),
        ("Cookies", "Oreo Cookie", "45.00", False, 0, "0.00"),
        ("Add-ons", "Seasalt Cream", "15.00", False, 0, "0.00"),
    ]
    for category_name, name, price, allow_addons, promo_qty, promo_price in products:
        POSProduct.objects.update_or_create(
            category=category_objects[category_name],
            name=name,
            defaults={
                "price": Decimal(price),
                "allow_addons": allow_addons,
                "promo_bundle_qty": promo_qty,
                "promo_bundle_price": Decimal(promo_price),
                "is_active": True,
            },
        )


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0018_material_costing_basis'),
    ]

    operations = [
        migrations.CreateModel(
            name='POSCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category_type', models.CharField(choices=[('DRINK', 'Drink'), ('STICKER', 'Sticker'), ('COOKIE', 'Cookie'), ('ADDON', 'Add-on'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'POS categories',
                'ordering': ['category_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='POSOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('customer_number', models.PositiveIntegerField(default=1)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cash_received', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('change_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Paid', 'Paid'), ('Void', 'Void')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='POSOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('category_name', models.CharField(max_length=120)),
                ('category_type', models.CharField(choices=[('DRINK', 'Drink'), ('STICKER', 'Sticker'), ('COOKIE', 'Cookie'), ('ADDON', 'Add-on'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.posorder')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='POSProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('description', models.TextField(blank=True)),
                ('image', models.FileField(blank=True, null=True, upload_to='pos_products/')),
                ('is_active', models.BooleanField(default=True)),
                ('allow_addons', models.BooleanField(default=False)),
                ('promo_bundle_qty', models.PositiveIntegerField(default=0, help_text='Optional bundle quantity. Example: 5 stickers.')),
                ('promo_bundle_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Optional bundle price. Example: 125.00.', max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='costing.poscategory')),
            ],
            options={
                'ordering': ['category__category_type', 'name'],
                'unique_together': {('category', 'name')},
            },
        ),
        migrations.CreateModel(
            name='POSOrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='costing.posorderitem')),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='addon_order_items', to='costing.posproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='posorderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='costing.posproduct'),
        ),
        migrations.CreateModel(
            name='POSQueueItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Preparing', 'Preparing'), ('Ready', 'Ready'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='costing.posorder')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='queue_items', to='costing.posorderitem')),
            ],
            options={
                'ordering': ['queued_at'],
            },
        ),
        migrations.RunPython(seed_pos_catalog, migrations.RunPython.noop),
    ]
