# Generated by Django 5.2.13 on 2026-05-18 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0019_poscategory_posorder_posorderitem_posproduct_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='customer_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
