# Generated by Django 5.2.13 on 2026-05-18 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0020_posorder_customer_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posorder',
            name='payment_method',
            field=models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], default='Cash', max_length=30),
        ),
    ]
