# Generated by Django 5.2.13 on 2026-05-29 16:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0021_posorder_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerOrderingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('average_preparation_minutes', models.PositiveIntegerField(default=2)),
                ('gcash_qr', models.FileField(blank=True, null=True, upload_to='payment_qr/')),
                ('maya_qr', models.FileField(blank=True, null=True, upload_to='payment_qr/')),
                ('bank_qr', models.FileField(blank=True, null=True, upload_to='payment_qr/')),
                ('gcash_instructions', models.TextField(blank=True, default='Scan the GCash QR code and upload your payment proof.')),
                ('maya_instructions', models.TextField(blank=True, default='Scan the Maya QR code and upload your payment proof.')),
                ('bank_instructions', models.TextField(blank=True, default='Send your bank transfer and upload your payment proof.')),
                ('notification_sound', models.FileField(blank=True, null=True, upload_to='notification_sounds/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer ordering setting',
                'verbose_name_plural': 'Customer ordering settings',
            },
        ),
        migrations.AddField(
            model_name='posorder',
            name='source',
            field=models.CharField(choices=[('Walk-in POS', 'Walk-in POS'), ('Customer Tablet', 'Customer Tablet'), ('Online Order', 'Online Order')], default='Walk-in POS', max_length=30),
        ),
        migrations.CreateModel(
            name='CustomerOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=40, unique=True)),
                ('customer_name', models.CharField(max_length=120)),
                ('contact_number', models.CharField(blank=True, max_length=50)),
                ('special_instructions', models.TextField(blank=True)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('payment_method', models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=30)),
                ('online_payment_channel', models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Maya', 'Maya'), ('Bank Transfer', 'Bank Transfer')], max_length=30)),
                ('payment_status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Waiting Verification', 'Waiting Verification'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], default='Unpaid', max_length=30)),
                ('order_status', models.CharField(choices=[('Pending Payment', 'Pending Payment'), ('Pending Verification', 'Pending Verification'), ('Preparing', 'Preparing'), ('Ready for Pickup', 'Ready for Pickup'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending Payment', max_length=30)),
                ('payment_proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('staff_notes', models.TextField(blank=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('preparing_at', models.DateTimeField(blank=True, null=True)),
                ('ready_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pos_order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_order', to='costing.posorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160)),
                ('category_name', models.CharField(max_length=120)),
                ('category_type', models.CharField(choices=[('DRINK', 'Drink'), ('STICKER', 'Sticker'), ('COOKIE', 'Cookie'), ('ADDON', 'Add-on'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_cost', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_profit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='costing.customerorder')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_order_items', to='costing.posproduct')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerOrderItemAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('addon_name', models.CharField(max_length=160)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('addon', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_addon_order_items', to='costing.posproduct')),
                ('order_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addons', to='costing.customerorderitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='OrderNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('message', models.TextField(blank=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='costing.customerorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(choices=[('Cash', 'Cash'), ('Online Payment', 'Online Payment')], max_length=30)),
                ('online_channel', models.CharField(blank=True, choices=[('GCash', 'GCash'), ('Maya', 'Maya'), ('Bank Transfer', 'Bank Transfer')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('Unpaid', 'Unpaid'), ('Waiting Verification', 'Waiting Verification'), ('Paid', 'Paid'), ('Refunded', 'Refunded')], max_length=30)),
                ('proof', models.FileField(blank=True, null=True, upload_to='payment_proofs/')),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='costing.customerorder')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=30)),
                ('new_status', models.CharField(max_length=30)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='costing.customerorder')),
            ],
            options={
                'verbose_name_plural': 'Order status histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
