# Generated by Django 5.2.13 on 2026-05-29 16:55

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0022_customerorderingsetting_posorder_source_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerorder',
            name='cash_received',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='customerorder',
            name='change_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
    ]
