# Generated by Django 5.2.13 on 2026-05-29 18:07

from django.db import migrations, models


def set_two_by_two_cricut_override(apps, schema_editor):
    StickerSize = apps.get_model('costing', 'StickerSize')
    StickerSize.objects.filter(width_in='2.00', height_in='2.00').update(cricut_fit_override=14)


def unset_two_by_two_cricut_override(apps, schema_editor):
    StickerSize = apps.get_model('costing', 'StickerSize')
    StickerSize.objects.filter(width_in='2.00', height_in='2.00', cricut_fit_override=14).update(cricut_fit_override=0)


class Migration(migrations.Migration):

    dependencies = [
        ('costing', '0023_customerorder_cash_received_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stickersize',
            name='cricut_fit_override',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Optional real-world Cricut fit per sheet. Leave 0 to calculate automatically.'),
        ),
        migrations.AddField(
            model_name='stickersize',
            name='full_fit_override',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='Optional full-sheet fit per sheet. Leave 0 to calculate automatically.'),
        ),
        migrations.RunPython(set_two_by_two_cricut_override, unset_two_by_two_cricut_override),
    ]
